### ISSUE TITLE
OTB-15acc is 60.6 using the pretrained weights

### ISSUE THREAD

**Issue by xxAna** [huanglianghua/GlobalTrack#11]
Thanks for your excellent work and your sharing. When I download your pretrained weights(qg_rcnn_r50_fpn_coco_got10k_lasot.pth) and testing it directly on OTB100, I found the acc is only 60.6, is that something wrong? Have you ever test it on OTB100. Waiting for your reply. Best wishes!

**Comment by huanglianghua** [comment]
Hi, the performance of GlobalTrack on OTB is indeed not high. I got a success score of 61.8% in my own test.

GlobalTrack shows its major advantage in long videos. Since its tracking error never accumulates, its performance will not degrade along with the time.

However, on short videos, especially those with multiple similar objects, GlobalTrack may fail in many frames, since it relies on NO temporal information.

We're still working on this problem and looking forward to developing a motion model with low cumulative errors. Thanks.

**Comment by xxAna** [comment]
Get it. Thank you for your timely reply and your warm heart.Best wishes!
